title: My firts blog hosted on GitHub
author: ddyfedd
email: dzsamboki.techwriter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My firts try at hosting a blog for possible future use, creating content about my progress as a professional Technical Writer.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ddyfedd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
